---
name: Check For Broken Links
author: Caleb Thompson (@mongocaleb)
description: 'Checks all links to make sure they are valid.'
branding:
  icon: 'check-square'
  color: 'white'

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        cd "${{github.action_path}}" 
        go build -v ./main.go 
        go run ./... --path ${{github.workspace}}
